-- ============================================================
-- Telas (Produccion): catalogo de telas + depositos/textiles.
-- Generado desde 'Planilla Info Textil.xlsx' (hoja 'Hoja 1').
-- Los COLORES NO se crean aca: salen de Dragonfish (DRAGONFISH_CENTRAL.Zoologic.DPCOLOR).
-- En Telas se guarda el codigo de color de Dragon (ColorCod = DPCOLOR.CODCOL). Sin hex.
-- Idempotente. Stock y compras (Fase 2) NO se crean aca.
-- ============================================================
SET NOCOUNT ON;

-- ---------- Catalogos propios ----------
IF OBJECT_ID('dbo.TelasDepositos','U') IS NULL
CREATE TABLE dbo.TelasDepositos (
    Id        INT IDENTITY(1,1) PRIMARY KEY,
    Nombre    NVARCHAR(100) NOT NULL,
    Eliminado BIT NOT NULL CONSTRAINT DF_TelasDepositos_Elim DEFAULT(0),
    Auditoria NVARCHAR(200) NULL
);
IF OBJECT_ID('dbo.TelasTextiles','U') IS NULL
CREATE TABLE dbo.TelasTextiles (
    Id        INT IDENTITY(1,1) PRIMARY KEY,
    Nombre    NVARCHAR(100) NOT NULL,
    Eliminado BIT NOT NULL CONSTRAINT DF_TelasTextiles_Elim DEFAULT(0),
    Auditoria NVARCHAR(200) NULL
);

-- ---------- Telas (ficha) ----------
IF OBJECT_ID('dbo.Telas','U') IS NULL
CREATE TABLE dbo.Telas (
    Id          INT IDENTITY(1,1) PRIMARY KEY,
    IdDeposito  INT NOT NULL,
    Material    NVARCHAR(200) NOT NULL,
    IdTextil    INT NULL,
    AnchoCm     DECIMAL(9,2) NULL,
    Composicion NVARCHAR(300) NULL,
    RindeMKg    DECIMAL(9,4) NULL,
    ColorCod    NVARCHAR(20) NULL,   -- codigo de color de Dragonfish (DPCOLOR.CODCOL); el nombre se resuelve por join
    -- Gramos/m2 calculado: 1000 / (Rinde * Ancho_metros). Igual que la planilla.
    GramosM2 AS (CASE WHEN ISNULL(RindeMKg,0) > 0 AND ISNULL(AnchoCm,0) > 0
                      THEN CAST(1000.0/(RindeMKg*(AnchoCm/100.0)) AS DECIMAL(9,2)) END),
    Eliminado   BIT NOT NULL CONSTRAINT DF_Telas_Elim DEFAULT(0),
    Auditoria   NVARCHAR(200) NULL,
    CONSTRAINT FK_Telas_Deposito FOREIGN KEY (IdDeposito) REFERENCES dbo.TelasDepositos(Id),
    CONSTRAINT FK_Telas_Textil   FOREIGN KEY (IdTextil)   REFERENCES dbo.TelasTextiles(Id)
);

-- ---------- Seed depositos ----------
IF NOT EXISTS (SELECT 1 FROM dbo.TelasDepositos WHERE Nombre = N'Filomena') INSERT INTO dbo.TelasDepositos (Nombre, Auditoria) VALUES (N'Filomena', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasDepositos WHERE Nombre = N'Milena') INSERT INTO dbo.TelasDepositos (Nombre, Auditoria) VALUES (N'Milena', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasDepositos WHERE Nombre = N'Ramon') INSERT INTO dbo.TelasDepositos (Nombre, Auditoria) VALUES (N'Ramon', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasDepositos WHERE Nombre = N'Vilma') INSERT INTO dbo.TelasDepositos (Nombre, Auditoria) VALUES (N'Vilma', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasDepositos WHERE Nombre = N'Vilma/Jorge') INSERT INTO dbo.TelasDepositos (Nombre, Auditoria) VALUES (N'Vilma/Jorge', N'Seed inicial | Excel');

-- ---------- Seed textiles/proveedores ----------
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Bultex') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Bultex', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Daniel') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Daniel', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Freeday') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Freeday', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Purpura') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Purpura', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Ramon') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Ramon', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Ramon (Contenedor Nuestro)', N'Seed inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.TelasTextiles WHERE Nombre = N'Uriel') INSERT INTO dbo.TelasTextiles (Nombre, Auditoria) VALUES (N'Uriel', N'Seed inicial | Excel');

-- ---------- Import de las 37 telas (Hoja 1). Color queda NULL (se asigna luego desde Dragon). ----------
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Remeria soft brush' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Remeria soft brush', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, N'96% poliester/ 4% elastano', 4.16, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Modal soft Liso' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Modal soft Liso', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'), 160.0, N'96% poliester/ 4% elastano', 3.45, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Ribb Soft Ada' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Ribb Soft Ada', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, N'96% poliester/ 4% elastano', 2.42, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Crep Sastrero' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Crep Sastrero', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, N'96% poliester/ 4% elastano', 3.5, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley Rustico' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley Rustico', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, NULL, 2.9, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley Vintage' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley Vintage', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, N'71% poliester/25% rayon/4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley Vintage' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley Vintage', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, N'71% poliester/25% rayon/4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley Vintage' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley Vintage', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'), 160.0, N'77% poly-17% rayon 6% spandex', 3.13, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Hawai vintage' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Hawai vintage', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 150.0, N'96% poliester/ 4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Hawai' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Hawai', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'), 150.0, NULL, 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Hawai Melange' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Hawai Melange', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 148.0, N'96% poliester/ 4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Waffle Vitage' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Waffle Vitage', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, N'96% poliester/ 4% elastano', 2.8, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Hawai XL' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Hawai XL', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 150.0, N'96% poliester/ 4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley soft' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley soft', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, NULL, 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma/Jorge' AND T.Material=N'Morley viscosa 2x2' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma/Jorge'), N'Morley viscosa 2x2', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, NULL, 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Magic' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Magic', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'), 160.0, N'100% poliester', 1.9, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Darlon Jersey Melange' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Darlon Jersey Melange', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'), 160.0, N'95% poliester/ 5% elastano', 2.75, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Micromorley 2x2' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Micromorley 2x2', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, NULL, 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Calcero' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Calcero', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'), 160.0, N'95% poliester/ 5%elastano', NULL, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Parachute' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Parachute', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'), 145.0, N'100% nylon', NULL, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Plush Doble Liso' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Plush Doble Liso', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'), 160.0, N'96% poliester/ 4% elastano', 3.0, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Bengalina' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Bengalina', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Freeday'), 146.0, N'77% rayon/ 20% poliamida/ 3% elastano', NULL, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Abercrombie' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Abercrombie', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'), 160.0, N'96% poliester/ 4% elastano + 100% poliester', 1.75, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Bruselas' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Bruselas', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Bultex'), 150.0, N'96% poliester/ 4% elastano', 4.43, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Milena' AND T.Material=N'Brodery' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Milena'), N'Brodery', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Daniel'), 160.0, NULL, 2.8, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Milena' AND T.Material=N'Modal soft Estampado' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Milena'), N'Modal soft Estampado', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon (Contenedor Nuestro)'), 150.0, N'96% poliester/ 4% elastano', NULL, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Jersey cardado' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Jersey cardado', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 90.0, NULL, 3.5, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Jersey cardado' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Jersey cardado', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 90.0, NULL, 3.5, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Frisa cardada' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Frisa cardada', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 90.0, NULL, 1.65, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Frisa invisible' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Frisa invisible', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 90.0, NULL, 1.6, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Darlon Ribb' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Darlon Ribb', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 160.0, N'90% poly 10% spandex', 2.36, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Morley diesel' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Morley diesel', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 160.0, N'75,3% poly 18% rayon 8%spandex', 2.6, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Waffle soft' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Waffle soft', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 160.0, N'96% poly 4% spandex', 3.13, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Filomena' AND T.Material=N'Plush liso' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Filomena'), N'Plush liso', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, NULL, 2.8, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma' AND T.Material=N'Morley vintage corderito' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma'), N'Morley vintage corderito', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Uriel'), 160.0, NULL, 2.2, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Vilma' AND T.Material=N'Waffle plush' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Purpura'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Vilma'), N'Waffle plush', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Purpura'), 160.0, N'95% poly 5% spandex', 1.8, N'Import inicial | Excel');
IF NOT EXISTS (SELECT 1 FROM dbo.Telas T JOIN dbo.TelasDepositos D ON T.IdDeposito=D.Id WHERE D.Nombre=N'Ramon' AND T.Material=N'Calcero "grueso"' AND ISNULL(T.IdTextil,-1)=ISNULL((SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'),-1)) INSERT INTO dbo.Telas (IdDeposito, Material, IdTextil, AnchoCm, Composicion, RindeMKg, Auditoria) VALUES ((SELECT Id FROM dbo.TelasDepositos WHERE Nombre=N'Ramon'), N'Calcero "grueso"', (SELECT Id FROM dbo.TelasTextiles WHERE Nombre = N'Ramon'), 160.0, NULL, 2.4, N'Import inicial | Excel');

SELECT (SELECT COUNT(*) FROM dbo.TelasDepositos) AS Depositos, (SELECT COUNT(*) FROM dbo.TelasTextiles) AS Textiles, (SELECT COUNT(*) FROM dbo.Telas) AS Telas;
